[package]
name = "project-release"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
lenient_semver = "0.4.2"
pep440 = "0.2.0"
semver = "1.0.16"

[dev-dependencies]
rstest = "0.16.0"
