name: Conventional commits

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  enforce-conventional-commits:
    runs-on: ubuntu-latest
    steps:

    - name: Check out the repo
      uses: actions/checkout@v3.5.0
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip3 install commitizen

    - name: Run commitizen on pull request
      if: ${{ github.event_name == 'pull_request' }}
      run: >
        cz check --rev-range
        ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}

    - name: Run commitizen on branch
      if: ${{ github.event_name == 'push' }}
      run: cz check --rev-range ${{ github.sha }}
